### ISSUE TITLE
Project Explain

### ISSUE THREAD

**Issue by felixabel684** [afzafri/CSC566-White-Blood-Cells-Detection-Matlab-Project#1]
helllo sir, can you explain your project? how rgb, cmyk, YCbCr have different result sir, thankyou

**Comment by felixabel684** [comment]
and why export data error sir?

**Comment by afzafri** [comment]
Sorry I no longer maintain this project.
You can read more on [Matlab community](https://www.mathworks.com/matlabcentral/answers/?search_origin=ans_leaf&term=white+blood+cell)
